jobs:
  run:
    if: "github.repository != github.event.pull_request.head.repo.full_name &&\n(\n\
      \  github.head_ref == 'master' ||\n  github.event.pull_request.head.repo.owner.type\
      \ != 'User'\n)\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: master_branch
      if: github.head_ref == 'master'
      uses: superbrothers/close-pull-request@v3
      with:
        comment: Please do not open pull requests from the `master` branch, create
          a new branch instead.
    - continue-on-error: true
      id: org_account
      if: github.event.pull_request.head.repo.owner.type != 'User' && steps.master_branch.outcome
        == 'skipped'
      uses: superbrothers/close-pull-request@v3
      with:
        comment: Please do not open pull requests from non-user accounts like organizations.
          Create a fork on a user account instead.
name: Close invalid PRs
on:
  repository_dispatch:
    types: trigger-ga___close_invalid_prs.yml
