jobs:
  bugs:
    concurrency:
      cancel-in-progress: true
      group: update-bugs-project-${{ github.event.issue.number }}
    if: 'github.event_name == ''issues'' && contains(github.event.*.labels.*.name,
      ''type: bug'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: authenticate
      name: authenticate
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ secrets.PROJECTS_APP_ID }}
        installation_id: '36153445'
        private_key: ${{ secrets.PROJECTS_PRIVATE_KEY }}
    - continue-on-error: true
      if: github.event.issue.state == 'open'
      name: Update open issue
      uses: PaperMC/update-projects-action@v0.2.0
      with:
        column-field: Status
        github-token: ${{ steps.authenticate.outputs.token }}
        label-to-column-map: "{\n  \"resolution: awaiting response\": \"\u231B Awaiting\
          \ Response\",\n  \"resolution: cannot reproduce\": \"Invalid\",\n  \"resolution:\
          \ duplicate\": \"Invalid\",\n  \"resolution: incomplete\": \"Invalid\",\n\
          \  \"resolution: invalid\": \"Invalid\",\n  \"resolution: superseded\":\
          \ \"Invalid\",\n  \"resolution: unsupported\": \"Invalid\",\n  \"resolution:\
          \ won't fix\": \"Invalid\",\n  \"resolution: works as intended\": \"Invalid\"\
          ,\n  \"status: accepted\": \"\u2705 Accepted\",\n  \"status: blocked\":\
          \ \"Needs Work\",\n  \"status: defer upstream\": \"Needs Work\",\n  \"status:\
          \ in progress\": \"Needs Work\",\n  \"status: input wanted\": \"Needs Work\"\
          ,\n  \"status: needs triage\": \"\U0001F551 Needs Triage\",\n  \"status:\
          \ rebase required\": \"Needs Work\",\n  \"status: unlikely\": \"\u2705 Accepted\"\
          \n}\n"
        project-url: https://github.com/orgs/PaperMC/projects/5/views/2
    - continue-on-error: true
      if: github.event.issue.state == 'closed'
      name: Update closed issue
      uses: PaperMC/update-projects-action@v0.2.0
      with:
        clear-on-no-match: false
        column-field: Status
        github-token: ${{ steps.authenticate.outputs.token }}
        label-to-column-map: "{\n  \"resolution: cannot reproduce\": \"Invalid\",\n\
          \  \"resolution: duplicate\": \"Invalid\",\n  \"resolution: incomplete\"\
          : \"Invalid\",\n  \"resolution: invalid\": \"Invalid\",\n  \"resolution:\
          \ superseded\": \"Invalid\",\n  \"resolution: unsupported\": \"Invalid\"\
          ,\n  \"resolution: won't fix\": \"Invalid\",\n  \"resolution: works as intended\"\
          : \"Invalid\",\n  \"status: accepted\": \"Done\",\n  \"status: needs triage\"\
          : \"Invalid\"\n}\n"
        project-url: https://github.com/orgs/PaperMC/projects/5/views/2
name: Update Projects
on:
  repository_dispatch:
    types: trigger-ga___projects.yml
