jobs:
  test-results:
    if: github.event.workflow_run.conclusion != 'skipped'
    name: Test Results
    permissions:
      actions: read
      checks: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download and Extract Artifacts
      uses: dawidd6/action-download-artifact@v3
      with:
        path: artifacts
        run_id: ${{ github.event.workflow_run.id }}
    - continue-on-error: true
      name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: off
        commit: ${{ github.event.workflow_run.head_sha }}
        event_file: artifacts/Event File/event.json
        event_name: ${{ github.event.workflow_run.event }}
        files: artifacts/**/*.xml
name: Test Results
on:
  repository_dispatch:
    types: trigger-ga___test_results.yml
permissions: {}
